# Generated by Django 6.0.6 on 2026-06-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='mensalista',
        ),
        migrations.AddField(
            model_name='jogador',
            name='tipo',
            field=models.CharField(choices=[('MENSALISTA', 'Mensalista'), ('DIARISTA', 'Diarista')], default='DIARISTA', max_length=20),
        ),
    ]
