# Generated by Django 6.0.6 on 2026-06-17 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_remove_jogador_mensalista_jogador_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=100)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Despesas',
            new_name='Despesa',
        ),
        migrations.AddField(
            model_name='jogador',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='tipo',
            field=models.CharField(choices=[('MENSALISTA', 'Mensalista'), ('DIARISTA', 'Diarista'), ('VISITANTE', 'Visitante')], default='DIARISTA', max_length=20),
        ),
        migrations.CreateModel(
            name='PresencaPelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(default=True)),
                ('pago', models.BooleanField(default=False)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacao', models.TextField(blank=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='financeiro.jogador')),
                ('pelada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='financeiro.pelada')),
            ],
            options={
                'unique_together': {('pelada', 'jogador')},
            },
        ),
    ]
