# Generated by Django 6.0.6 on 2026-06-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_pelada_rename_despesas_despesa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presencapelada',
            options={'ordering': ['pelada', 'tipo_lista', 'posicao_lista']},
        ),
        migrations.AlterUniqueTogether(
            name='presencapelada',
            unique_together={('pelada', 'jogador')},
        ),
        migrations.AddField(
            model_name='presencapelada',
            name='posicao_lista',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presencapelada',
            name='tipo_lista',
            field=models.CharField(choices=[('GOLEIRO', 'Goleiro'), ('LISTA', 'Lista Principal'), ('RESERVA_CASA', 'Reserva de Casa'), ('RESERVA_VISITANTE', 'Reserva Visitante')], default='LISTA', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='presencapelada',
            unique_together={('pelada', 'jogador'), ('pelada', 'tipo_lista', 'posicao_lista')},
        ),
    ]
