# Generated by Django 6.0.6 on 2026-06-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_presencapelada_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelada',
            name='custo_quadra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
