# Generated by Django 6.0.6 on 2026-06-17 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_pelada_custo_quadra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='presenca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='financeiro.presencapelada'),
        ),
    ]
