# Generated by Django 6.0.6 on 2026-06-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_pagamento_presenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(default='Galera FC', max_length=100)),
                ('valor_diaria_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limite_lista_principal', models.PositiveIntegerField(default=24)),
                ('limite_goleiros', models.PositiveIntegerField(default=4)),
                ('limite_reservas_casa', models.PositiveIntegerField(default=5)),
                ('limite_reservas_visitantes', models.PositiveIntegerField(default=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
