# Generated by Django 6.0.6 on 2026-06-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_configuracaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencapelada',
            name='isento',
            field=models.BooleanField(default=False),
        ),
    ]
